import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@providers/theme.provider";
import { getSessionWithUser } from "@shared/lib/supabase/server.supabase";
import AppHeader from "@ui/layouts/AppHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session, user } = await getSessionWithUser();
  console.log({ session });
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body
        className={`antialiased min-h-[100dvh] grid grid-rows-[auto_1fr_auto] bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppHeader session={session} user={user} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
