import {
  ChartNoAxesCombined,
  ChevronDown,
  CodeXml,
  DraftingCompass,
  Footprints,
  Goal,
  Lightbulb,
  List,
  LucideIcon,
  Rocket,
  ArrowLeft,
  Save,
  BookOpenCheck,
  Asterisk,
  ImageOff,
} from "lucide-react";

export const ICON_PALETTE = {
  ChartNoAxesCombined,
  ChevronDown,
  CodeXml,
  DraftingCompass,
  Footprints,
  Goal,
  Lightbulb,
  List,
  Rocket,
  ArrowLeft,
  Save,
  BookOpenCheck,
  Asterisk,
  ImageOff,
} satisfies Record<string, LucideIcon>; // icons-palette.ts에서
